secure_vote/core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    #------------------------Registration------------------------#
    path('login/', views.login_page, name="login"),
    path('login_otp/', views.login_otp, name="login_otp"),
    path('logout/', views.logout_page, name="logout"),
    path('register/', views.register_page, name="register"),
    path('register_otp/', views.register_otp, name="register_otp"),
    
    #------------------------Voting------------------------#
    path('', views.home, name='home'),
    path('success/', views.success, name='success'),
    path('mine_success/', views.mine_success, name='mine_success'),
    path('mine/', views.mine, name='mine'),
    path('voting/', views.voting, name='voting'),
    path('all_votes/', views.all_votes, name='all_votes'),
    path('submit/', views.submit, name='submit'),
    path('count_votes/', views.count_votes, name='count_votes'),
    path('chart_votes/', views.chart_votes, name='chart_votes'),

    #------------------------Blockchain------------------------#
    path('change_node/', views.change_node, name='change_node'),
    path('register_node/', views.register_node, name='register_node'),
    path('connected_node/', views.connected_node, name='connected_node'),

    #------------------------Blockchain------------------------#
    # path('new_transaction/', views.new_transaction, name='new_transaction'),
    # path('get_chain/', views.get_chain, name='get_chain'),
    # path('mine_block/', views.mine_block, name='mine_block'),
    # path('pending_transaction/', views.pending_transaction, name='pending_transaction'),

    # path('tamper/', views.tamper, name='tamper'),
]

secure_vote/secure_vote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

secure_vote/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now


class UniqueID(models.Model):
    unique_id = models.CharField(max_length=10, primary_key=True)
    name = models.CharField(max_length=200,)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=10, unique=True)
    age = models.IntegerField()
    address = models.CharField(max_length = 100)
    pincode = models.CharField(max_length = 6)
    country = models.CharField(max_length = 100)
    city = models.CharField(max_length = 100)
    state = models.CharField(max_length = 100)
    c_id = models.CharField(max_length=10, null=True)
    
    def __str__(self):
        return self.unique_id


class Constituency(models.Model):
    c_id = models.CharField(max_length=10, primary_key=True)
    c_name = models.CharField(max_length=100, null=True)
    pub_date = models.DateTimeField('date published', default=now)
    is_active = models.BooleanField(default=False)
    node_address = models.URLField(max_length=200, null=True)

    def __str__(self):
        return self.c_name


class Party(models.Model):
    party_id = models.CharField(max_length=10, primary_key=True)
    candidate = models.CharField(max_length=100, null=True)
    party_name = models.CharField(max_length=100, null=True)
    party_pic = models.CharField(max_length=500, blank=True)
    constituency = models.ForeignKey(Constituency, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.candidate} | {self.party_name}"


class RegisteredVoters(AbstractUser):
    username = models.CharField(max_length=10, primary_key=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    phone = models.CharField(max_length=10, unique=True, null=True)
    age = models.IntegerField(default=0)
    otp = models.CharField(max_length=6)
    account_verified = models.BooleanField(default=False)
    vote_done = models.BooleanField(default=False)
    c_id = models.CharField(max_length=10, null=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELD = []

    def __str__(self):
        return self.username

secure_vote/core/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import authenticate, login, logout

import json
import requests
import datetime
import random
from hashlib import sha256

from .models import  Constituency, Party, RegisteredVoters, UniqueID
from .blockchain import Blockchain


# ------------Initializing blockchain-----------------------

# blockchain = Blockchain()

# blockchain.create_genesis_block()

# candidates = Party.objects.all()
# candidates = list(candidates)
# blockchain.create_candidates(candidates)

BLOCKCHAIN_NODE_ADDRESS = "http://127.0.0.1:5000"


# ------------Registration And Login-----------------------

def send_otp(phone, otp):
    print(f"phone = {phone} and otp = {otp}")


def register_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        age = request.POST.get('age')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')

        try:
            unique_id_details = UniqueID.objects.get(unique_id=username)
        except:
            messages.error(request, 'Unique id doesnot exists')
            return redirect('register')

        if username != unique_id_details.unique_id:
            messages.error(request, 'Unique id is invalid')
            return redirect('register')

        if email != unique_id_details.email:
            messages.error(request, 'email does not match unique id email')
            return redirect('register')

        if phone != unique_id_details.phone:
            messages.error(request, 'phone no does not match unique id email')
            return redirect('register')

        if int(age) < 18 or int(unique_id_details.age) < 18:
            messages.error(request, 'You must be 18+ to vote')
            return redirect('register')

        if int(age) != int(unique_id_details.age):
            messages.error(request, 'Age does not match with unique_id age')
            return redirect('register')

        if password != password2:
            messages.error(request, 'Passwords do not match')
            return redirect('register')

        if RegisteredVoters.objects.filter(username=username).exists():
            messages.error(request, 'Voter already registered')
            return redirect('register')

        if RegisteredVoters.objects.filter(email=email).exists():
            messages.error(request, 'That email is already registered')
            return redirect('register')

        if RegisteredVoters.objects.filter(phone=phone).exists():
            messages.error(request, 'That phone no is already registered')
            return redirect('register')

        try:
            otp = str(random.randint(100000, 999999))
            print("cid:  ", unique_id_details.c_id)
            user = RegisteredVoters.objects.create_user(username=username, 
                                                        name=name, 
                                                        email=email, 
                                                        phone=phone, 
                                                        age=age, 
                                                        password=password, 
                                                        otp=otp, 
                                                        c_id=unique_id_details.c_id)
            user.save()
            send_otp(phone, otp)
            request.session['phone'] = phone
            messages.success(request, 'You are now registered and can log in')
            return redirect('register_otp')
        except: 
            messages.error(request, 'error while registering')
            return redirect('register')
    else:
        return render(request, 'register.html')


def register_otp(request):
    phone = request.session['phone']
    if request.method == 'POST':
        otp = request.POST.get('otp')
        voter = RegisteredVoters.objects.filter(phone=phone).first()

        if otp == voter.otp:
            voter.account_verified = True
            voter.save()
            messages.success(request, 'OTP verified, You can now log in')
            return redirect('login')
        else:
            print('Wrong OTP')
            messages.error(request, 'You entered wrong OTP')
            return render(request, 'register_otp.html', {'phone': phone})
    
    return render(request, 'register_otp.html', {'phone': phone})


def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        voter = RegisteredVoters.objects.get(username=username)
        if voter.vote_done:
            messages.error(request, 'You have already voted')
            return redirect('login')

        try:
            constituency = Constituency.objects.get(c_id=voter.c_id)
        except:
            messages.error(request, 'Error in contituency, please contact admin')
            return redirect('login')

        if not constituency.is_active:
            messages.error(request, 'Voting in your constituency is currently not active')
            return redirect('login')
        
        if not voter.account_verified:
            messages.error(request, 'Account not verified, Please verify your account')
            otp = str(random.randint(100000, 999999))
            voter.otp = otp
            voter.save()
            phone = voter.phone
            request.session['phone'] = phone
            send_otp(phone, otp)
            return redirect('register_otp')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            phone = user.phone
            otp = str(random.randint(100000, 999999))
            user.otp = otp
            user.save()
            request.session['phone'] = phone
            send_otp(phone, otp)
            messages.success(request, 'Verify to login')
            return redirect('login_otp')
        else:
            messages.error(request, 'Invalid credentials')
            return redirect('login')
    else:
        return render(request, 'login.html')


def login_otp(request):
    phone = request.session['phone']
    if request.method == 'POST':
        otp = request.POST.get('otp')
        voter = RegisteredVoters.objects.filter(phone=phone).first()

        if otp == voter.otp:
            login(request, voter)
            messages.success(request, 'OTP verified, Login successful')
            return redirect('home')
        else:
            print('Wrong OTP')
            messages.error(request, 'You entered wrong OTP')
            return render(request, 'login_otp.html', {'phone': phone})
    
    return render(request, 'login_otp.html', {'phone': phone})


def logout_page(request):
    logout(request)
    messages.success(request, 'You are now logged out')
    return redirect('home')


# ------------Voting Phase-----------------------

def home(request):
    if request.user.is_authenticated:
        global BLOCKCHAIN_NODE_ADDRESS
        constituency = Constituency.objects.get(c_id=request.user.c_id)
        BLOCKCHAIN_NODE_ADDRESS = constituency.node_address
        print("constituency address: ", constituency.node_address)
        print("CONSTITUENCY ADDRESS: ", BLOCKCHAIN_NODE_ADDRESS)
    return render(request, 'landing.html')


@login_required(login_url='login')
def voting(request):
    constituency = Constituency.objects.get(c_id=request.user.c_id)
    if request.user.vote_done:
        messages.error(request, 'You cannot vote more than once')
        return redirect('home')
    
    if not constituency.is_active:
        messages.error(request, 'Voting in your constituency is currently not active')
        return redirect('home')
        
    else:
        return render(request, 'voting.html', {'constituency': constituency})


@login_required(login_url='login')
def submit(request):
    if request.method == 'POST':
        data = request.POST

        if request.user.is_authenticated:
            voter = RegisteredVoters.objects.get(username=request.user.username)
            voter_hash_string = str(request.user.username) + str(request.user.email) + str(request.user.name) + str(request.user.phone) + str(request.user.age)
            voter_hashed_value = sha256(voter_hash_string.encode()).hexdigest()

            vote_transaction = {
                "candidate": request.POST.get('candidate'),
                "voterhash": voter_hashed_value
            }

            response = requests.post(f"{BLOCKCHAIN_NODE_ADDRESS}/new_transaction/", json=vote_transaction, headers={'Content-type': 'application/json'})

            response_data = response.json()
            print(response_data)

            if response.status_code == 201:
                voter.vote_done = True
                # voter.save()  # change this 
                return render(request, 'success.html', {'voter_details': data})
            else:
                return render(request, 'error.html', {'error_message': response_data['error']})
        else:
            return render(request, 'error.html', {'error_message': "NOT VALID"})


@login_required(login_url='login')
def success(request):
    return render(request, 'success.html')


@login_required(login_url='login')
def mine(request):
    requests.get(f"{BLOCKCHAIN_NODE_ADDRESS}/mine_block/")
    return redirect('mine_success')


@login_required(login_url='login')
def mine_success(request):
    return render(request, 'mine_success.html')


# ------------Result-----------------------

def all_votes(request):
    vote_data = []
    response = requests.get(f"{BLOCKCHAIN_NODE_ADDRESS}/chain")

secure_vote/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- bootstrap -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!--Chart js-->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"
      integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw="
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css"
      integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E="
      crossorigin="anonymous"
    />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css"
    />
    <title>Secure voting</title>
  </head>
  <body>
    {%block scripts%} {%endblock scripts%}
    <div style="position: relative; min-height: 90vh">
      <div style="padding-bottom: 2.5rem">
        <header>
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
              <a class="navbar-brand" href="{% url 'home' %}">Secure voting</a>
              <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
                  <a class="nav-item nav-link" href="{% url 'count_votes' %}"
                    >Result</a
                  >
                  <a class="nav-item nav-link" href="{% url 'all_votes' %}"
                    >All Votes</a
                  >
                </ul>
                {% if user.is_superuser %}
                <a
                  class="nav-item nav-link link-light"
                  href="{% url 'register_node' %}"
                  >Register Node</a
                >
                <a
                  class="nav-item nav-link link-light"
                  href="{% url 'change_node' %}"
                  >Change Node Node</a
                >
                <a
                  class="nav-item nav-link link-light"
                  href="{% url 'connected_node' %}"
                  >Connected Node</a
                >
                {% endif %} {% if user.is_authenticated %}
                <a
                  class="nav-item nav-link link-light"
                  href="{% url 'voting' %}"
                  >Vote</a
                >
                <a
                  type="button"
                  class="btn btn-outline-warning px-3"
                  href="{% url 'logout'%}"
                  >Logout</a
                >
                {% else %}
                <a
                  type="button"
                  class="btn btn-outline-light mx-2"
                  href="{% url 'login'%}"
                  >Login</a
                >
                <a
                  type="button"
                  class="btn btn-warning mx-2"
                  href="{% url 'register'%}"
                  >Register</a
                >
                {% endif %}
              </div>
            </div>
          </nav>
        </header>
        {% if messages %}
        <ul style="max-width: 600px; margin: 0 auto" class="mt-3 container">
          {% for message in messages %}
          <div class="alert {{ message.tags }} alert-dismissible" role="alert">
            {{ message }}
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="alert"
              aria-label="Close"
            ></button>
          </div>
          {% endfor %}
        </ul>
        {% endif %} {% block content %}{% endblock %}
      </div>
      <footer
        style="position: absolute; bottom: 0; width: 100%; height: 2.5rem"
        class="py-2 my-2"
      >
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item">
            <a href="{% url 'home' %}" class="nav-link px-2 text-muted">Home</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'voting' %}" class="nav-link px-2 text-muted"
              >Vote</a
            >
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link px-2 text-muted">About</a>
          </li>
          <li class="nav-item">
            <a
              href="https://github.com/rit77777/final-year-project"
              class="nav-link px-2 text-muted"
              >Github</a
            >
          </li>
          <li class="nav-item">
            <a href="{% url 'count_votes' %}" class="nav-link px-2 text-muted"
              >Result</a
            >
          </li>
        </ul>
        <p class="text-center text-muted">Secure Voting</p>
      </footer>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

secure_vote/core/templates/change_node_success.html
{% extends "base.html" %} {% block content %}

<section style="max-width: 900px; margin: 0 auto" class="container">
  <div class="px-4 py-5 my-5 text-center card animated fadeIn">
    <div class="card-body">
      <h1 class="display-5">✅</h1>
      <h1 class="display-5 fw-bold">Node Changed Successful</h1>
      <div class="col-lg-12 mx-auto">
        <p class="lead mb-4">
          All votes will now be counted at <b>{{node_address}}</b>
        </p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
          <a
            type="button"
            class="btn btn-dark btn-lg px-5 gap-3"
            href="{% url 'home' %}"
            >Return to home</a
          >
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

secure_vote/core/templates/connected_node.html
{% extends "base.html" %} {% block content %}

<section style="max-width: 900px; margin: 0 auto" class="container">
  <div class="px-4 py-5 my-5 text-center card animated fadeIn">
    <div class="card-body">
      <h1 class="display-5 fw-bold">Active Node</h1>
      <div class="col-lg-12 mx-auto">
        <p class="lead mb-4"><b>{{connected_node}}</b> is now active</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
          <a
            type="button"
            class="btn btn-dark btn-lg px-5 gap-3"
            href="{% url 'home' %}"
            >Return to home</a
          >
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

secure_vote/core/templates/count_votes.html
{% extends "base.html" %} {% block content %}
<section style="max-width: 900px; margin: 0 auto" class="container mt-4">
  <div class="card text-center mb-3">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="true"
            href="{% url 'count_votes'%}"
            >Table</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'chart_votes'%}">Chart</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="px-4 py-2 mt-3 mb-5 text-center">
        <h1 class="display-5 fw-bold">Result</h1>
        <table class="table table-striped">
          <thead>
            <tr>
              <th style="text-align: center" scope="col">Candidate Name</th>
              <th style="text-align: center" scope="col">No of Votes</th>
            </tr>
          </thead>
          <tbody>
            {% for key, value in vote_count.items %}
            <tr>
              <td>{{ key }}</td>
              <td>{{ value }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
{% endblock %}

secure_vote/core/templates/count_votes_graph.html
{% extends "base.html" %} {%block scripts%}
<script>
  $(document).ready(function(){
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: [{%for data in names%}'{{data}}',{%endfor%}],
                datasets: [{
                    label: '# of votes',
                    data: [{%for data in count%}{{data}},{%endfor%}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
    	});
  });
</script>
{%endblock scripts%} {% block content %}
<section style="max-width: 900px; margin: 0 auto" class="container mt-4">
  <div class="card text-center mb-3">
    <div class="card-header">
      <ul class="nav nav-tabs card-header-tabs">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'count_votes'%}">Table</a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="true"
            href="{% url 'chart_votes'%}"
            >Chart</a
          >
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="py-2 mt-3 mb-5 text-center">
        <h1 class="display-5 fw-bold">Result</h1>
        <canvas id="myChart" width="400" height="150"></canvas>
      </div>
    </div>
  </div>
</section>
{% endblock %}

secure_vote/core/templates/error.html
{% extends "base.html" %} {% block content %}
<section>
  <div class="px-4 py-5 my-5 text-center">
    <div class="alert alert-danger" role="alert">
      <h1 class="alert-heading">Error</h1>
      <p>{{error_message}}</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a
          type="button"
          class="btn btn-light btn-lg px-5 gap-3"
          href="{% url 'home' %}"
          >Back</a
        >
      </div>
    </div>
  </div>
</section>
{% endblock %}

secure_vote/core/templates/landing.html
{% extends "base.html" %} {% block content %}
<section style="max-width: 750px; margin: 0 auto" class="container mt-4">
  {% if user.is_authenticated %}
  <div class="">
    <div class="alert alert-primary" role="alert">
      <h4 class="alert-heading">Voter Detail</h4>
      <p>
        <b>UniqueID :</b> {{user.username}} | <b>Name :</b> {{user.name}} |
        <b>Age :</b> {{user.age}} | <b> Phone:</b> {{user.phone}} |
        <b>Constituency:</b> {{user.c_id}}
      </p>
    </div>
  </div>
  {% endif %}
  <div class="px-2 py-5 my-5 text-center">
    <img
      class="d-block mx-auto mb-4"
      src="https://upload.wikimedia.org/wikipedia/en/thumb/d/d4/Election_Commission_of_India_logo.svg/1200px-Election_Commission_of_India_logo.svg.png"
      alt=""
      width="72"
      height="57"
    />
    <h1 class="display-5 fw-bold">Vote securely</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">
        A secure online voting system built using blockchain
      </p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a
          type="button"
          class="btn btn-dark btn-lg px-5 gap-3"
          href="{% url 'voting'%}"
          >Vote</a
        >
      </div>
    </div>
  </div>
</section>
{% endblock content %}

secure_vote/core/templates/login.html
{% extends "base.html" %} {% block content %}
<section style="max-width: 500px; margin: 0 auto" class="container">
  <form class="mt-4" action="{% url 'login' %}" method="POST">
    {% csrf_token %}
    <h1 class="mb-2">Login</h1>
    <div class="mb-2">
      <label for="username" class="form-label">UniqueID</label>
      <input
        type="text"
        name="username"
        class="form-control"
        id="username"
        required
      />
    </div>
    <div class="mb-3">
      <label for="password" class="form-label">Password</label>
      <input
        type="password"
        name="password"
        class="form-control"
        id="password"
        required
      />
    </div>
    <button type="submit" class="btn btn-dark">Submit</button>
  </form>
  <div class="mt-2">
    <div class="text-muted">
      Dont Have An Account?
      <a class="ml-2" href="{% url 'register' %}">Register</a>
    </div>
  </div>
</section>
{% endblock content %}

secure_vote/core/templates/login_otp.html
{% extends "base.html" %} {% block content %}
<section style="max-width: 500px; margin: 0 auto" class="container">
  <div class="card mt-5">
    <div class="card-header">
      <h5 class="mb-2">OTP is sent to Your Mobile No</h5>
    </div>
    <div class="card-body">
      <form action="{% url 'login_otp' %}" method="POST">
        {% csrf_token %}
        <div class="mb-2">
          <label for="otp" class="form-label">Enter OTP</label>
          <input
            type="password"
            name="otp"
            class="form-control"
            id="otp"
            required
          />
        </div>
        <div class="mb-3">
          <div class="text-muted">
            Dont Have An Account?
            <a class="ml-2" href="{% url 'register' %}">Register</a>
          </div>
        </div>
        <button type="submit" class="btn btn-dark">Submit</button>
      </form>
    </div>
  </div>
</section>
{% endblock content %}

secure_vote/core/templates/register_node.html
{% extends "base.html" %} {% block content %}

<section style="max-width: 900px; margin: 0 auto" class="container">
  <div class="px-4 py-5 my-5 text-center card animated fadeIn">
    <div class="card-body">
      <form action="{% url 'register_node' %}" method="POST">
        {% csrf_token %}

        <h1 class="display-5 fw-bold mb-4">Register Node</h1>
        <div class="mb-2">
          <label for="nodeaddr" class="form-label">Node Address</label>
          <input
            type="text"
            name="nodeaddr"
            class="form-control"
            id="nodeaddr"
            required
          />
        </div>

        <button type="submit" class="btn btn-dark btn-lg px-5 gap-3 mt-2">
          Submit
        </button>
      </form>
    </div>
  </div>
</section>

{% endblock %}

secure_vote/core/templates/voting.html
{% extends "base.html" %} {% block content %}
<section
  style="max-width: 700px; margin: 0 auto"
  class="mt-4"
  class="container"
>
  <form action="{% url 'submit' %}" method="POST">
    {% csrf_token %}
    <h1 class="fw-bold mb-3">Cast your vote</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th style="text-align: center" scope="col">Party Logo</th>
          <th style="text-align: center" scope="col">Party Name</th>
          <th style="text-align: center" scope="col">Candidate Name</th>
          <th style="text-align: center" scope="col">Vote</th>
        </tr>
      </thead>
      <tbody>
        {% for candidate in constituency.party_set.all %}
        <tr>
          <td style="text-align: center">
            <img
              src="{{ candidate.party_pic }}"
              alt=""
              height="42"
              width="42"
            />
          </td>
          <td style="text-align: center">{{ candidate.party_name }}</td>
          <td style="text-align: center">{{ candidate.candidate }}</td>
          <td style="text-align: center">
            <button
              name="candidate"
              type="submit"
              value="{{candidate.candidate}}"
              class="btn btn-dark"
            >
              Vote
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </form>
</section>

{% endblock content %}